version: "3"

services:
  traefik:
    image: traefik:v2.1
    container_name: "traefik"
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      # - "--entrypoints.websecure.address=:443"
      # - "--certificatesresolvers.leresolver.acme.httpchallenge=true"
      # - "--certificatesresolvers.leresolver.acme.httpchallenge.entrypoint=web"
      # - "--certificatesresolvers.leresolver.acme.email=${letsencrypt_admin_email}"
      # - "--certificatesresolvers.leresolver.acme.email=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./letsencrypt:/letsencrypt:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
